Fix unused-but-set-global error
```
/home/build-user/swift-corelibs-libdispatch/src/queue.c:6549:29: error: variable '_dispatch_program_is_probably_callback_driven' set but not used [-Werror,-Wunused-but-set-global]
 6549 | DISPATCH_STATIC_GLOBAL(bool _dispatch_program_is_probably_callback_driven);
```

Clang 23 suddenly caught this on the Swift CI builders. This global is
read only under `#ifndef __linux__`.

(cherry picked from commit d545f73a398604cd4cd495ca5b1e74f24d0d72e5)